{
 "title": "CrossZone Network Monitor",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "src_namespace",
    "query": {
     "query": "label_values(pod_cross_zone_network_traffic_bytes_total, src_namespace)"
    }
   },
   {
    "name": "dst_namespace",
    "query": {
     "query": "label_values(pod_cross_zone_network_traffic_bytes_total, dst_namespace)"
    }
   },
   {
    "name": "src_pod",
    "query": {
     "query": "label_values(pod_cross_zone_network_traffic_bytes_total, src_pod)"
    }
   },
   { "name": "interval", "query": "10m,1h,6h,1d,1w" },
   { "name": "datasource", "label": "Data Source", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Total Traffic Pod-to-Pod",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(13, rate(pod_cross_zone_network_traffic_bytes_total{src_namespace=~\"$src_namespace\", dst_namespace=~\"$dst_namespace\", src_pod=~\"$src_pod\"}[1d]))",
     "legendFormat": "{{src_pod}} - {{dst_pod}}"
    }
   ]
  },
  {
   "title": "Pod-to-Pod Cross Zone traffic",
   "type": "timeseries",
   "description": "Traffic between pods between different availability zones. Such data transfer is billable by the cloud!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "topk(13, sort_desc(rate(pod_cross_zone_network_traffic_bytes_total{src_namespace=~\"$src_namespace\", dst_namespace=~\"$dst_namespace\", src_pod=~\"$src_pod\"}[1d])))",
     "legendFormat": "{{src_pod}}[{{src_zone}}] - {{dst_pod}}[{{dst_zone}}]"
    }
   ]
  },
  {
   "title": "Pod-to-Pod Cross Zone traffic cumulative",
   "type": "timeseries",
   "description": "Traffic between pods between different availability zones. Such data transfer is billable by the cloud!",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "topk(13, sort_desc(increase(pod_cross_zone_network_traffic_bytes_total{src_namespace=~\"$src_namespace\", dst_namespace=~\"$dst_namespace\", src_pod=~\"$src_pod\"}[$__interval])))",
     "legendFormat": "{{src_pod}}[{{src_zone}}] - {{dst_pod}}[{{dst_zone}}]"
    }
   ]
  },
  {
   "title": "Total Cross-Zone DataTransfer",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(pod_cross_zone_network_traffic_bytes_total{src_namespace=~\"$src_namespace\", dst_namespace=~\"$dst_namespace\", src_pod=~\"$src_pod\"}[$__interval]))",
     "legendFormat": "Cross-Zone Traffic"
    }
   ]
  },
  {
   "title": "Total Traffic between pods",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "sum(rate(pod_network_traffic_bytes_total{src_namespace=~\"$src_namespace\", dst_namespace=~\"$dst_namespace\", src_pod=~\"$src_pod\"}[$__interval]))",
     "legendFormat": "Total Traffic"
    }
   ]
  }
 ]
}